CREATE TABLE IF NOT EXISTS product
(
  uuid VARCHAR(255) NOT NULL CONSTRAINT pk_product PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  article_id INTEGER NOT NULL,
  last_updated TIMESTAMP NOT NULL DEFAULT NOW()
);